Exploratory Data Analysis
Understanding the dataset to explore how data is present in the DB and if there is a need of creatong some aggregated tables that can help with:
1)Vendor selection for profitability
2)Product Pricing Optimization

In [14]:
import pandas as pd
import sqlite3

In [15]:
import os

for root, dirs, files in os.walk(r"C:\Users\SHRADDHA"):
    if "inventory.db" in files:
        print(os.path.join(root, "inventory.db"))

C:\Users\SHRADDHA\inventory.db
C:\Users\SHRADDHA\logs\inventory.db

In [16]:
import sqlite3

conn = sqlite3.connect("inventory.db")

cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

print(cursor.fetchall())

[('vendor_sales_summary',), ('begin_inventory',), ('end_inventory',), ('purchases',), ('purchase_prices',), ('sales',), ('vendor_invoice',)]

In [17]:
#checking tables present in the database
tables=pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)
tables

                   name
0  vendor_sales_summary
1       begin_inventory
2         end_inventory
3             purchases
4       purchase_prices
5                 sales
6        vendor_invoice

In [18]:
import sqlite3

conn = sqlite3.connect(r"C:\Users\SHRADDHA\inventory.db")

In [19]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

                   name
0  vendor_sales_summary
1       begin_inventory
2         end_inventory
3             purchases
4       purchase_prices
5                 sales
6        vendor_invoice

In [20]:
import pandas as pd

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

print(tables)

                   name
0  vendor_sales_summary
1       begin_inventory
2         end_inventory
3             purchases
4       purchase_prices
5                 sales
6        vendor_invoice

In [21]:
pd.read_sql("SELECT COUNT(*) AS count FROM purchases", conn)

     count
0  2372474

In [22]:
for table in tables['name']:
    print('-'*50,f'{table}','-'*50)
    print('Count of records:',pd.read_sql(f"select count(*) as count from {table}",conn)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",conn))

-------------------------------------------------- vendor_sales_summary --------------------------------------------------
Count of records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,5101919.51,672819.31,142049.0,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,4819073.49,561512.37,160247.0,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,4538120.60,461140.15,187140.0,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,4475972.88,420050.01,200412.0,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,4223107.62,545778.28,135838.0,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchases --------------------------------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- sales --------------------------------------------------
Count of records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [23]:
purchases = pd.read_sql_query("SELECT * FROM purchases WHERE VendorNumber = 4466",conn)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [24]:
purchase_prices = pd.read_sql_query("""SELECT * FROM purchase_prices WHERE VendorNumber = 4466""",conn)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [25]:
vendor_invoice = pd.read_sql_query("""SELECT * FROM vendor_invoice WHERE VendorNumber = 4466""",conn)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [26]:
sales = pd.read_sql_query("""SELECT * FROM sales WHERE VendorNo = 4466""",conn)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [27]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [28]:
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [29]:
vendor_invoice['PONumber'].nunique()

55

In [30]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [31]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

1)The purchases table contains actual purchase data,including the date of purchase,products(brands)purchased by vendors,the amount paid(in dollars)and the quantity purchased.
2)The purchase price column is derived from the purchase_prices table,which provides product-wise actual and purchase prices.The combination of vendor and brand is unique in this table.
3)The vendor_invoice table aggregates data from the purchase s table ,summarizing qty and dollar amounts,along with an additional column for freight.This table maintains uniqueness based on vendor and PO number
4)The sales table captures  actual sales transactions,detailing the brands purchased by vendors,the qunatity sold,the selling price,and the revenue earned.

As the data that we need for analysis is distributed in different tables,we need to create a summary table containing:
1)purchase transactions made by vendors
2)sales transaction data
3)freight costs for each vendor
4)actual product prices from vendors

In [32]:
freight_summary = pd.read_sql_query("""SELECT VendorNumber,SUM(Freight) as FreightCost FROM vendor_invoice
GROUP BY VendorNumber""",conn)

In [33]:
freight_summary

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [34]:
pd.read_sql_query("""SELECT 
p.VendorNumber,
p.VendorName,
p.Brand,
p.PurchasePrice,
pp.Volume,
pp.Price as ActualPrice,
SUM(p.Quantity) as TotalPurchaseQuantity,
SUM(p.Dollars) as TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
ON p.Brand=pp.Brand
WHERE p.PurchasePrice>0
GROUP BY p.VendorNumber,p.VendorName,p.Brand
ORDER BY TotalPurchaseDollars""",conn)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [35]:
pd.read_sql_query("""SELECT
VendorNo,
Brand,
SUM(SalesDollars) AS TotalSalesDollars,
SUM(SalesPrice) AS TotalSalesPrice,
SUM(SalesQuantity) AS TotalSalesQuantity,
SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo,Brand 
ORDER BY TotalSalesDollars""",conn)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,1.98,0.99,2,0.10
3,3924,9123,1.98,0.99,2,0.10
4,10050,3623,1.98,1.98,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,135838,249587.83
11268,3960,4261,4475972.88,420050.01,200412,368242.80
11269,17035,8068,4538120.60,461140.15,187140,343854.07
11270,4425,3405,4819073.49,561512.37,160247,294438.66
11271,1128,1233,5101919.51,672819.31,142049,260999.20

In [36]:
import time
start=time.time()
final_table=pd.read_sql_query("""SELECT
pp.VendorNumber,
pp.Brand,
pp.Price AS ActualPrice,
pp.PurchasePrice,
SUM(s.SalesQuantity) AS TotalSalesQuantity,
SUM(s.SalesDollars) AS TotalSalesDollars,
SUM(s.SalesPrice) AS TotalSalesPrice,
SUM(s.ExciseTax) AS TotalExciseTax,
SUM(vi.Quantity) AS TotalPurchaseQuantity,
SUM(vi.Dollars) AS TotalPurchaseDollars,
SUM(vi.Freight) AS TotalFreightCost
FROM purchase_prices pp
JOIN sales s
ON pp.VendorNumber=s.VendorNo
AND pp.Brand=s.Brand
JOIN vendor_invoice vi
ON pp.VendorNumber=vi.VendorNumber
GROUP BY pp.VendorNumber,pp.Brand,pp.Price,pp.PurchasePrice
""",conn)
end=time.time()

DatabaseError: Execution failed on sql 'SELECT
pp.VendorNumber,
pp.Brand,
pp.Price AS ActualPrice,
pp.PurchasePrice,
SUM(s.SalesQuantity) AS TotalSalesQuantity,
SUM(s.SalesDollars) AS TotalSalesDollars,
SUM(s.SalesPrice) AS TotalSalesPrice,
SUM(s.ExciseTax) AS TotalExciseTax,
SUM(vi.Quantity) AS TotalPurchaseQuantity,
SUM(vi.Dollars) AS TotalPurchaseDollars,
SUM(vi.Freight) AS TotalFreightCost
FROM purchase_prices pp
JOIN sales s
ON pp.VendorNumber=s.VendorNo
AND pp.Brand=s.Brand
JOIN vendor_invoice vi
ON pp.VendorNumber=vi.VendorNumber
GROUP BY pp.VendorNumber,pp.Brand,pp.Price,pp.PurchasePrice
': database or disk is full

The above Query is taking a lot of time hence we need to optimize like for example if a query is there and it runs in 5-8 min but we want our data and incoming data time is 4-5 minutes and then it will lead to data leak and hence we need to optimize it.So we will make diff tables and then we have joined the tables.

In [ ]:
vendor_sales_summary=pd.read_sql_query("""WITH FreightSummary AS (
SELECT 
VendorNumber,
SUM(Freight) AS FreightCost
FROM vendor_invoice
GROUP BY VendorNumber
),

PurchaseSummary AS (
SELECT
p.VendorNumber,
p.VendorName,
p.Brand,
p.Description,
p.PurchasePrice,
pp.Price AS ActualPrice,
pp.Volume,
SUM(p.Quantity) as TotalPurchaseQuantity,
SUM(p.Dollars) as TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
ON p.Brand=pp.Brand
WHERE p.PurchasePrice>0
GROUP BY p.VendorNumber,p.VendorName,p.Brand,p.PurchasePrice,p.Description,pp.Price,pp.Volume
),

SalesSummary AS (
SELECT
VendorNo,
Brand,
SUM(SalesDollars) AS TotalSalesDollars,
SUM(SalesPrice) AS TotalSalesPrice,
SUM(SalesQuantity) AS TotalSalesQuantity,
SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo,Brand
)

SELECT
ps.VendorNumber,
ps.VendorName,
ps.Brand,
ps.Description,
ps.PurchasePrice,
ps.ActualPrice,
ps.Volume,
ps.TotalPurchaseQuantity,
ps.TotalPurchaseDollars,
ss.TotalSalesDollars,
ss.TotalSalesPrice,
ss.TotalSalesQuantity,
ss.TotalExciseTax,
fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
ON ps.VendorNumber=ss.VendorNo
AND ps.Brand=ss.Brand
LEFT JOIN FreightSummary fs
ON ps.VendorNumber=fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC""",conn)

In [ ]:
vendor_sales_summary

This query generates a vendor-wise sales and purchase summary, which is valuable for:

Performance Optimization:

1)The query involves heavy joins and aggregations on large datasets like sales and purchases.
2)Storing the pre-aggregated results avoids repeated expensive computations.
3)Helps in analyzing sales, purchases, and pricing for different vendors and brands.
4)Future benefits of storing this data for faster dashboarding and reporting.
5)Instead of running expensive queries each time, dashboards can fetch data quickly from the vendor_sales_summary table.

In [ ]:
vendor_sales_summary.dtypes

In [ ]:
vendor_sales_summary.isnull().sum()

In [ ]:
vendor_sales_summary.head()

In [ ]:
vendor_sales_summary['VendorName'].unique()#object type so check for the unneccessary spaces

In [ ]:
vendor_sales_summary['Description'].unique()

In [ ]:
vendor_sales_summary['Volume']=vendor_sales_summary['Volume'].astype('float64')

In [ ]:
vendor_sales_summary.fillna(0,inplace=True)

In [ ]:
vendor_sales_summary['VendorName']=vendor_sales_summary['VendorName'].str.strip()

In [ ]:
vendor_sales_summary['GrossProfit']=vendor_sales_summary['TotalSalesDollars']-vendor_sales_summary['TotalPurchaseDollars']

In [ ]:
vendor_sales_summary['GrossProfit'].min()

In [ ]:
vendor_sales_summary['ProfitMargin']=(vendor_sales_summary['GrossProfit']/vendor_sales_summary['TotalSalesDollars'])*100

In [ ]:
vendor_sales_summary['StockTurnover']=vendor_sales_summary['TotalSalesQuantity']/vendor_sales_summary['TotalPurchaseQuantity']

In [ ]:
vendor_sales_summary['SalesToPurchaseRatio']=vendor_sales_summary['TotalSalesDollars']/vendor_sales_summary['TotalPurchaseDollars']

In [ ]:
#again saving the table

In [ ]:
cursor=conn.cursor()

In [ ]:
cursor.execute("""CREATE TABLE vendor_sales_summary(
VendorNumber INT,
VendorName VARCHAR(100),               
Brand INT,                   
Description VARCHAR(100),              
PurchasePrice DECIMAL(10,2),         
ActualPrice DECIMAL(10,2),             
Volume                  
TotalPurchaseQuantity INT,   
TotalPurchaseDollars DECIMAL(15,2),     
TotalSalesDollars DECIMAL(15,2),        
TotalSalesPrice DECIMAL(15,2),          
TotalSalesQuantity INT,      
TotalExciseTax DECIMAL(15,2),          
FreightCost DECIMAL(15,2),
GrossProfit DECIMAL(15,2),
ProfitMargin DECIMAL(15,2),
StockTurnover DECIMAL(15,2),
SalesToPurchaseRatio DECIMAL(15,2),
PRIMARY KEY(VendorNumber,Brand)
);
""")

In [ ]:
pd.read_sql_query("select * from vendor_sales_summary",conn)

In [ ]:
#adding values to the table
vendor_sales_summary.to_sql('vendor_sales_summary',conn,if_exists='replace',index=False)

In [40]:
import glob
print(glob.glob("*.py"))

['get_vendor_summary.py', 'ingestion_db.py']

In [54]:
#hence to schedule the repetitive tasks we do scripting
import sqlite3
import pandas as pd
import logging
def ingest_db(df, table_name, conn):
    """
    Store a DataFrame into the SQLite database.
    """
    df.to_sql(
        table_name,
        conn,
        if_exists="replace",
        index=False
    )
    logging.info(f"{table_name} ingested successfully.")

logging.basicConfig(
    filename="logs/get_vendor_summary.log",
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    filemode="a",
    force=True      # <-- Important in Jupyter
)

def create_vendor_summary(conn):
    #this function will merge the diff tables to the overall vendor summary and adding new columns in the resultant data
    vendor_sales_summary=pd.read_sql_query("""WITH FreightSummary AS (
SELECT 
VendorNumber,
SUM(Freight) AS FreightCost
FROM vendor_invoice
GROUP BY VendorNumber
),

PurchaseSummary AS (
SELECT
p.VendorNumber,
p.VendorName,
p.Brand,
p.Description,
p.PurchasePrice,
pp.Price AS ActualPrice,
pp.Volume,
SUM(p.Quantity) as TotalPurchaseQuantity,
SUM(p.Dollars) as TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
ON p.Brand=pp.Brand
WHERE p.PurchasePrice>0
GROUP BY p.VendorNumber,p.VendorName,p.Brand,p.PurchasePrice,p.Description,pp.Price,pp.Volume
),

SalesSummary AS (
SELECT
VendorNo,
Brand,
SUM(SalesDollars) AS TotalSalesDollars,
SUM(SalesPrice) AS TotalSalesPrice,
SUM(SalesQuantity) AS TotalSalesQuantity,
SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo,Brand
)

SELECT
ps.VendorNumber,
ps.VendorName,
ps.Brand,
ps.Description,
ps.PurchasePrice,
ps.ActualPrice,
ps.Volume,
ps.TotalPurchaseQuantity,
ps.TotalPurchaseDollars,
ss.TotalSalesDollars,
ss.TotalSalesPrice,
ss.TotalSalesQuantity,
ss.TotalExciseTax,
fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
ON ps.VendorNumber=ss.VendorNo
AND ps.Brand=ss.Brand
LEFT JOIN FreightSummary fs
ON ps.VendorNumber=fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC""",conn)
    return vendor_sales_summary

#for cleaning the data
def clean_data(df):

    # changing datatype to float
    df['Volume'] = df['Volume'].astype(float)

    # filling missing values
    df.fillna(0, inplace=True)

    # removing spaces
    df['VendorName'] = df['VendorName'].str.strip()
    df['Description'] = df['Description'].str.strip()

    # creating new columns
    df['GrossProfit'] = df['TotalSalesDollars'] - df['TotalPurchaseDollars']

    df['ProfitMargin'] = (
        df['GrossProfit'] / df['TotalSalesDollars']
    ) * 100

    df['StockTurnover'] = (
        df['TotalSalesQuantity'] / df['TotalPurchaseQuantity']
    )

    df['SalesToPurchaseRatio'] = (
        df['TotalSalesDollars'] / df['TotalPurchaseDollars']
    )

    return df

if __name__=='__main__':
    #creating database connection
    conn=sqlite3.connect('inventory.db')

    logging.info('Creating Vendor Summary Table.....')
    summary_df=create_vendor_summary(conn)
    logging.info(summary_df.head())

    logging.info('Cleaning Data.....')
    clean_df=clean_data(summary_df)
    logging.info(clean_df.head())

    logging.info('Ingesting data....')
    ingest_db(clean_df,'vendor_sales_summary',conn)
    logging.info('Completed')

In [53]:
import os

print(os.getcwd())
print(os.path.exists("logs/get_vendor_summary.log"))

C:\Users\SHRADDHA
False